"""Primera migración

Revision ID: 0d0a60bfd369
Revises: 
Create Date: 2025-11-14 11:43:07.186551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d0a60bfd369'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docente',
    sa.Column('id_docente', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_docente'),
    sa.UniqueConstraint('cedula')
    )
    op.create_index(op.f('ix_docente_id_docente'), 'docente', ['id_docente'], unique=False)
    op.create_table('estudiante',
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_estudiante'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_estudiante_id_estudiante'), 'estudiante', ['id_estudiante'], unique=False)
    op.create_table('curso',
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('cupo_estudiante', sa.Integer(), nullable=False),
    sa.Column('horario', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id_docente', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_docente'], ['docente.id_docente'], ),
    sa.PrimaryKeyConstraint('id_curso')
    )
    op.create_index(op.f('ix_curso_id_curso'), 'curso', ['id_curso'], unique=False)
    op.create_table('asistencia',
    sa.Column('id_asistencia', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id_curso'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_asistencia')
    )
    op.create_table('calificacion',
    sa.Column('id_calificacion', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.Column('tipo_evaluacion', sa.Integer(), nullable=True),
    sa.Column('nota', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id_curso'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_calificacion')
    )
    op.create_table('estudiante_curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.Column('fecha_inscripcion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id_curso'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudiante_curso_id'), 'estudiante_curso', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estudiante_curso_id'), table_name='estudiante_curso')
    op.drop_table('estudiante_curso')
    op.drop_table('calificacion')
    op.drop_table('asistencia')
    op.drop_index(op.f('ix_curso_id_curso'), table_name='curso')
    op.drop_table('curso')
    op.drop_index(op.f('ix_estudiante_id_estudiante'), table_name='estudiante')
    op.drop_table('estudiante')
    op.drop_index(op.f('ix_docente_id_docente'), table_name='docente')
    op.drop_table('docente')
    # ### end Alembic commands ###
