"""add configuracion table

Revision ID: df71eff2d6d8
Revises: 6bf1301c89d6
Create Date: 2025-11-15 02:12:45.918331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df71eff2d6d8'
down_revision: Union[str, Sequence[str], None] = '6bf1301c89d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estudiante_curso_id'), table_name='estudiante_curso')
    op.drop_table('estudiante_curso')
    op.drop_table('asistencia')
    op.drop_table('calificacion')
    op.drop_index(op.f('ix_curso_id_curso'), table_name='curso')
    op.drop_table('curso')
    op.drop_index(op.f('ix_docente_id_docente'), table_name='docente')
    op.drop_table('docente')
    op.drop_index(op.f('ix_estudiante_id_estudiante'), table_name='estudiante')
    op.drop_table('estudiante')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudiante',
    sa.Column('id_estudiante', sa.INTEGER(), server_default=sa.text("nextval('estudiante_id_estudiante_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombres', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apellidos', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cedula', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('correo', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('estado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_estudiante', name='estudiante_pkey'),
    sa.UniqueConstraint('cedula', name='estudiante_cedula_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('correo', name='estudiante_correo_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_estudiante_id_estudiante'), 'estudiante', ['id_estudiante'], unique=False)
    op.create_table('docente',
    sa.Column('id_docente', sa.INTEGER(), server_default=sa.text("nextval('docente_id_docente_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombres', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apellidos', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cedula', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('especialidad', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('estado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_docente', name='docente_pkey'),
    sa.UniqueConstraint('cedula', name='docente_cedula_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_docente_id_docente'), 'docente', ['id_docente'], unique=False)
    op.create_table('curso',
    sa.Column('id_curso', sa.INTEGER(), server_default=sa.text("nextval('curso_id_curso_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('cupo_estudiante', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('horario', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id_docente', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_docente'], ['docente.id_docente'], name='curso_id_docente_fkey'),
    sa.PrimaryKeyConstraint('id_curso', name='curso_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_curso_id_curso'), 'curso', ['id_curso'], unique=False)
    op.create_table('calificacion',
    sa.Column('id_calificacion', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_estudiante', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_curso', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_evaluacion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nota', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id_curso'], name=op.f('calificacion_id_curso_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], name=op.f('calificacion_id_estudiante_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_calificacion', name=op.f('calificacion_pkey'))
    )
    op.create_table('asistencia',
    sa.Column('id_asistencia', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_estudiante', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_curso', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id_curso'], name=op.f('asistencia_id_curso_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], name=op.f('asistencia_id_estudiante_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_asistencia', name=op.f('asistencia_pkey'))
    )
    op.create_table('estudiante_curso',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_estudiante', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_curso', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_inscripcion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id_curso'], name=op.f('estudiante_curso_id_curso_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], name=op.f('estudiante_curso_id_estudiante_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('estudiante_curso_pkey'))
    )
    op.create_index(op.f('ix_estudiante_curso_id'), 'estudiante_curso', ['id'], unique=False)
    # ### end Alembic commands ###
